### ISSUE TITLE
Allow circuits to use sha256 for identity hash commitments

### ISSUE THREAD

**Issue by corydickson** [semaphore-protocol/semaphore#107]
Currently, the circuits use groth16 for both the identity hash and the external nullifier. This calculation can be quite expensive if an existing semaphore merkle tree were to migrate to a new proving system like plonky2. 

Would the team be open to supporting both groth16 and sha256 for identity hashes? The change would entail adding constraints to the current circuits for sha256 but should still keep the hashes themselves agnostic to either. It's not clear to me to support this if it's necessary to also extend this change to the external nullifier. Thoughts?

**Comment by cedoor** [comment]
Hi, this is not our priority at the moment. However, I think that we will explore other proof systems in the long term, and we will consider how to better organize the code so that it is backward compatible.
