### ISSUE TITLE
CalculateIdentityCommitment has one redundant hash

### ISSUE THREAD

**Issue by ChihChengLiang** [semaphore-protocol/semaphore#110]
In CalculateSecret, we have `secret = hash(identityNullifier + identityTrapdoor)`

but in CalculateIdentityCommitment, we compute `idcommit = hash(secret) = hash(hash(identityNullifier + identityTrapdoor))`

It looks like the second hash is redundant, we can remove it to gain some performance.

Thank @vivianjeng for discovering this issue.

**Comment by cedoor** [comment]
Hey @ChihChengLiang , I think we're using that `secret` hash to make Semaphore identities compatible with [RLN identities](https://github.com/Rate-Limiting-Nullifier/rln_circuits/blob/7e4f068efa0fee954722da93fc545a2454dac6ac/circuits/rln-base.circom#L6).

**Comment by ChihChengLiang** [comment]
I see, thank you @cedoor. Closing now.
