### ISSUE TITLE
Suggestion: Identity data commitments

### ISSUE THREAD

**Issue by TheFrozenFire** [semaphore-protocol/semaphore#111]
**Is your feature request related to a problem? Please describe.**
In some use-cases, it would be necessary for users of a Semaphore to be able to associate data attributes with their identity in a group. For instance, a messaging solution may only wish for users to signal certain messages (e.g. to a particular group) if their identity has certain attributes (e.g. age >= 18).

**Describe the solution you'd like**
Semaphore identities being inserted should include a commitment to an arbitrary data payload. When a message is being signalled from the Semaphore, that data commitment should be salted by a random value and output publicly. An application can then rely upon this salted data commitment to generate an additional proof that the data commitment contains the attributes that are required for a signalling a given message, without disclosing which identity contains that data commitment, or needing to modify the base Semaphore circuit to include those proprietary rules.

A potential avenue to explore is whether this can be achieved without modifying the Semaphore circuit itself. For instance, if the identity data commitment could be specified as the identity trapdoor (making sure to include some random data within the commitment preimage for security), then the application-specific proof could simply reuse the `CalculateNullifierHash` component - essentially using the external nullifier as the commitment salt - to prove that the data attribute proof pertains to the same identity used in the signal proof, and then use data from the trapdoor commitment for attribute proofs.

**Comment by AtHeartEngineer** [comment]
@cedoor where can I find the commit to this?

**Comment by cedoor** [comment]
Hey @AtHeartEngineer, this has not been implemented. Not in this repo at least.
