### ISSUE TITLE
Group membership expiration

### ISSUE THREAD

**Issue by numtel** [semaphore-protocol/semaphore#120]
**Describe your project**
[Coinpassport.net](https://coinpassport.net) offers a simple interface for anybody with an Ethereum wallet to link their passport to a specific account using the Stripe Identity service. Coinpassport's verification contract stores a salted hash of the country code, passport number and expiration date.

I would like to build a layer on top of this verification contract where users can opt into an group and then connect a different account to their identity in order to provide full anonymity beyond the current psuedonymity but as far as I can tell, there is no way for members of this Semaphore group to expire when their passport expires. I'm not even sure that this would be possible with the level of anonymity provided by Semaphore groups. Am I correct in my understanding or is there some way to do this?

Also, after reading Miguel's #98 issue, it seems that having users continually join the group may not be possible?

**Comment by cedoor** [comment]
Hi @numtel ,

> Am I correct in my understanding or is there some way to do this?

When a member is added to the group, the expiration date of the passport could also be saved by associating it with the identity commitment only. The admin will then remove the identity commitment when the passport has expired. Could this solution work?

> Also, after reading Miguel's https://github.com/semaphore-protocol/semaphore/issues/98 issue, it seems that having users continually join the group may not be possible?

It's possible, but a root history is needed. I'm working on it right now.
