### ISSUE TITLE
Vulnerability allowing double spend

### ISSUE THREAD

**Issue by poma** [semaphore-protocol/semaphore#16]
Looks like in [Semaphore.sol#L83](https://github.com/kobigurk/semaphore/blob/602dd57abb43e48f490e92d7091695d717a63915/semaphorejs/contracts/Semaphore.sol#L83) we don't check that nullifier length is less than field modulus. So `nullifier_hash + 21888242871839275222246405745257275088548364400416034343698204186575808495617` will also pass snark proof verification if it fits into uint256, allowing double spend.

Example of 2 transactions:

https://kovan.etherscan.io/tx/0x5e8bf35ad76a086b98698f9d20bd7b6397ccc90aa6f85c1c5debc0262be5458a
https://kovan.etherscan.io/tx/0x9a47cc8daec9d0a5e9a860ada77730190124f9864a5917dcb8f41773d94cfc1a

**Comment by kobigurk** [comment]
This is confirmed. Thanks a lot for this report. We'll reply here when it's fixed.

**Comment by kobigurk** [comment]
Fix merged!
