### ISSUE TITLE
Deploy Semaphore contracts on Sepolia

### ISSUE THREAD

**Issue by ligi** [semaphore-protocol/semaphore#183]
**Provide data related to the network**

* Name
 Sepolia
* Chain id
 11155111
* URL
sepolia.org

**Reasons why it is important for Semaphore to be deployed on this network.**

Currently testnet-wise semaphore is only deployed on goerli. 
Sepolia is intended to replace goerli for application testing.
See e.g. @q9f 's talk from @efdevcon

![image](https://user-images.githubusercontent.com/111600/207047011-3aad81a2-3d13-483b-9c73-49ccbd143691.png)

also see: https://blog.ethereum.org/2022/06/21/testnet-deprecation

**Comment by q9f** [comment]
ref https://github.com/eth-clients/sepolia

**Comment by cedoor** [comment]
Thanks @ligi, we'll deploy Semaphore on Sepolia as soon as we release Semaphore v3!
