### ISSUE TITLE
Create a Semaphore explorer for on-chain groups

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#184]
**Description**:

The explorer will be a read-only client-side web application that uses the [Semaphore subgraph](https://github.com/semaphore-protocol/subgraph), in particular the `SemaphoreSubgraph` class of the [`@semaphore-protocol/data`](https://github.com/semaphore-protocol/semaphore/tree/main/packages/data) library, to fetch on-chain data from several networks (i.e. Goerli, Mumbai, Optimism Goerli, Arbitrum One) and display it in an intuitive and user-friendly way. The design and code can be refined later. The idea is to have a working demo.

Some of the key features that the explorer should include are:
* A search bar that allows users to search for specific on-chain groups by ID
* A dashboard that displays key statistics about Semaphore groups, such as the total number of groups, the total number of group members, the total number of verified proofs
* A detailed view of each group that displays information such as the group's members, the group's verified proofs

**Suggestions**:

The application might be built using [Vite](https://vitejs.dev/) and [React](https://reactjs.org/) with [ChakraUI](https://chakra-ui.com/). Github might be used as a hosting service. Possible projects to take inspiration from are:
* https://etherscan.io/
* https://explorer.unirep.io/
* https://chainlook.xyz/

**Comment by ai-slave** [comment]
Something that is still on the radar?

**Comment by cedoor** [comment]
> Something that is still on the radar?

Of course 👍🏽

**Comment by andyguzmaneth** [comment]
@ai-slave feel free to put it on your name! Let us know through the channels if you have any questions

**Comment by ameya-deshmukh** [comment]
@aguzmant103 still open ser? :)

**Comment by cedoor** [comment]
> @aguzmant103 still open ser? :)

Still open 👍🏽

**Comment by cedoor** [comment]
@calebanderson526 I think you have to interact here for me to assign you the task.
