### ISSUE TITLE
Too many signals set. 

### ISSUE THREAD

**Issue by dugubuyan** [semaphore-protocol/semaphore#249]
**Describe the bug**
An error happened: Too many signals set. 

**To Reproduce**
the code is below:
const group = new Group(21886654534243)

const identity = new Identity("secret-message")
console.log(identity.toString())
const identityCommitment = identity.getCommitment()
group.addMember(identityCommitment)
console.log(group)

const externalNullifier = group.root
const signal = 1

const fullProof = await generateProof(identity, group, externalNullifier, signal, {
    zkeyFilePath: "./semaphore.zkey",
    wasmFilePath: "./semaphore.wasm"
})

**Expected behavior**
When generateProof is called, the error happened

**Technologies (please complete the following information):**

-   Node v16.17.1
-   NPM version: 8.15.0

**Additional context**

**Comment by cedoor** [comment]
Hi @dugubuyan,

which version of Semaphore are you using? Are the `zkey`/`wasm` files the right ones (`treeDepth=20`)?

**Comment by dugubuyan** [comment]
the Semaphore version is 3.0.0, and the zkey/wasm are the right ones

**Comment by cedoor** [comment]
> the Semaphore version is 3.0.0, and the zkey/wasm are the right ones

Hey, I just tried the same code with v3.0.0 and it works. I'm using the following zk files:

* https://www.trusted-setup-pse.org/semaphore/20/semaphore.zkey
* https://www.trusted-setup-pse.org/semaphore/20/semaphore.wasm

When I tried to use the wrong zkey/wasm files (with depth = 16), it gave me your same error.

**Comment by dugubuyan** [comment]
Thanks a lot.
It seems I have download the wrong zk files.

**Comment by dugubuyan** [comment]
done

**Comment by cedoor** [comment]
> Thanks a lot. It seems I have download the wrong zk files.

No worries 👍🏽
