### ISSUE TITLE
Contracts requiring specific Solidity version

### ISSUE THREAD

**Issue by cichaczem** [semaphore-protocol/semaphore#259]
**Describe the bug**

I'm using Semaphore via the git submodule. I'm working on switching from V2 to V3. When using V3, I had to downgrade the entire project from the latest Solidity version to 0.8.4 required in [SemaphoreVerifier](https://github.com/semaphore-protocol/semaphore/blob/d001dd928be9adb826000768ae5dfaef140d06e2/contracts/base/Verifier.sol#L19) to make my contract compile.

[Previous Verifier](https://github.com/semaphore-protocol/semaphore/blob/d001dd928be9adb826000768ae5dfaef140d06e2/contracts/base/Verifier.sol#L19) worked fine with higher versions.

**Questions**
Is the specific Solidity version necessary for the library to work?
Or is it possible to enable a higher version to compile this code, like it's done in [Pairing.sol](https://github.com/semaphore-protocol/semaphore/blob/main/packages/contracts/contracts/base/Pairing.sol#L9)

**Comment by cedoor** [comment]
Hey @cichaczem, the reason why we are using fixed versions is here: https://github.com/semaphore-protocol/semaphore/pull/116.

Basically, it's a best practice to reduce possible vulnerabilities with other untested versions.

**Comment by cichaczem** [comment]
Thank you for the answer. That makes sense.

Are you planning to bump the version to the latest or anything higher than 0.8.4?

**Comment by cedoor** [comment]
> Thank you for the answer. That makes sense.
> 
> Are you planning to bump the version to the latest or anything higher than 0.8.4?

No problem. Not yet, we'll probably bump it with Semaphore v4, but that release is still far away.
