### ISSUE TITLE
Stringified identities are ambiguously encoded

### ISSUE THREAD

**Issue by vimwitch** [semaphore-protocol/semaphore#260]
**Describe the bug**
The `nullifier` and `trapdoor` in a zk identity are hex encoded without a `0x` prefix. This is ambiguous because a decimal string can be a valid hex string, and a hex string can be a valid decimal string.

**Expected behavior**
String encoded identities are non-ambiguously encoded.

**Comment by cedoor** [comment]
@vimwitch thank you 👍🏽 It'll be part of v3.2.0!
