### ISSUE TITLE
Add `secretHash` getter to `@semaphore-protocol/identity`

### ISSUE THREAD

**Issue by vimwitch** [semaphore-protocol/semaphore#294]
**Is your feature request related to a problem? Please describe.**
In out proofs we need to provide the identity secret as an input. This is not a property on the `Identity` class so we need to extend it to implement this.

**Describe the solution you'd like**
Add a `secretHash` getter.

**Describe alternatives you've considered**

**Additional context**

**Comment by cedoor** [comment]
Right! Let me know if you're already working on it. I can also do it 👍🏽
