### ISSUE TITLE
Use same contract address across all networks

### ISSUE THREAD

**Issue by atomniketh** [semaphore-protocol/semaphore#298]
It would be helpful to use the same contract address for deployed contracts across all networks.

This can be useful for testing purposes and helpful to users interacting with Semaphore addresses across various networks.

For reference: https://docs.alchemy.com/docs/how-to-deploy-a-contract-to-the-same-address-on-multiple-networks

**Comment by atomniketh** [comment]
Thank you!

**Comment by atomniketh** [comment]
Is this going to be reflected on: https://semaphore.appliedzkp.org/docs/deployed-contracts ? The x.sol address should be the same across all networks. Looks like maybe you are actively updating it now?

**Comment by cedoor** [comment]
@atomniketh Yes, it's still on the `dev` branch. We are testing everything before releasing a `v3.6.0` stable version 👍🏽
