### ISSUE TITLE
Timing attacks in identity package

### ISSUE THREAD

**Issue by vimwitch** [semaphore-protocol/semaphore#307]
**Describe the bug**
The javascript `BigInt` implementation does not run in constant time. The semaphore identity derivation system is vulnerable to timing attacks.

**To Reproduce**
n/a

**Expected behavior**
Identity derivation happens in constant time.

**Additional context**
I'm not sure the best approach to solve this. One idea that may help is hashing random values when doing identity secret/commitment calculation.

~~e.g. when I calculate my identity secret my machine hashes my private keys, along with `N` other random values (discarding the random outputs).~~

This wouldn't work, the differences would still be the same over time.

**Comment by cedoor** [comment]
Hey @vimwitch, can you give an example of that attack? The identities are generated client-side, so should an attacker access your local device to measure the right time?

**Comment by vimwitch** [comment]
Right i was imagining a malicious website could query the identity commitment many times, or something like that. But the attack only works when signing different data, so they would have to time the zk proof generation. Either way i think it's out of scope of this package.
