### ISSUE TITLE
Input Aliasing issue

### ISSUE THREAD

**Issue by 0xsaya** [semaphore-protocol/semaphore#317]
Looks like in [Semaphore.sol#L181](https://github.com/semaphore-protocol/semaphore/blob/0cb0ef3514bc35890331379fd16c7be071ada4f6/packages/contracts/contracts/Semaphore.sol#L181) we don't check that nullifier length is less than field modulus. So nullifier_hash + 21888242871839275222246405745257275088548364400416034343698204186575808495617 will also pass snark proof verification if it fits into uint256, allowing double spend.
And the same problem is https://github.com/semaphore-protocol/semaphore/issues/16

**Comment by cedoor** [comment]
Hey @effify, it should check it here: https://github.com/semaphore-protocol/semaphore/blob/0cb0ef3514bc35890331379fd16c7be071ada4f6/packages/contracts/contracts/base/Pairing.sol#L94
Can you confirm?

**Comment by 0xsaya** [comment]
Right, you guys have fixed it.thank you !
