### ISSUE TITLE
Semaphore package leaks handles, prevents node from exiting

### ISSUE THREAD

**Issue by dcposch** [semaphore-protocol/semaphore#318]
**Describe the bug**

My Mocha unit tests hang unless I specify `--exit` to kill the test process after each suite.

It looks like this may be because Semaphore leaks some resources.

**To Reproduce**

Write any test or script that verifies a Semaphore proof. At the end, add:

```ts
const foo = (process as any)._getActiveHandles();
console.log(foo);
```

You'll see that this includes a bunch of mysterious `MessagePort` handles.

**Expected behavior**

Should show exactly two handles, corresponding to `stdin/stdout`.

**Technologies (please complete the following information):**

-   Node.js version 20
-   NPM version 9.6.4
-   Solidity version N/A

**Comment by dcposch** [comment]
Using `@semaphore-protocol/{group,identity,proof}` version 3.2.3

**Comment by vplasencia** [comment]
Hello @dcposch! It seems to be related to `snarkjs` which is used in the `@semaphore-protocol/proof` package to generate and verify a proof.

**Comment by cedoor** [comment]
https://github.com/semaphore-protocol/semaphore/issues/736#issuecomment-2027490466

This issue is related to `snarkjs`, but Semaphore could provide a function to "terminate" it.

**Comment by Chirag-S-Kotian** [comment]
is it solved or not?

**Comment by cedoor** [comment]
Hi @Chirag-S-Kotian, we are actually going to close this issue.  Devs can use `ffjavascript` to get the curve and terminate it: https://github.com/semaphore-protocol/semaphore/blob/3ed6c38587b58851d4b8ec138a9979f7f716a885/packages/proof/tests/index.test.ts#L18

We'll add documentation to explain how to solve this issue.

Re: https://github.com/semaphore-protocol/semaphore/issues/897
