### ISSUE TITLE
Proving ownership of identity commitment

### ISSUE THREAD

**Issue by sirpy** [semaphore-protocol/semaphore#320]
Is there a way for a user to proof that he owns a specific commitment?
For example if the group admin wants to remove a member upon his request without keeping a database of user->commitments?

**Comment by cedoor** [comment]
Hey @sirpy, there's no easy way now unfortunately, but we're going to include this feature in Semaphore V4!

There might be a solution in some cases tho. If your users join a group with their identity commitments and an Ethereum account, you could use that Ethereum account to prove the identity ownership by signing the identity commitment.

**Comment by sirpy** [comment]
ok thanks. that solution still requires keeping a user/address->commitment list.
