### ISSUE TITLE
semaphoreEthers function for checking individual group membership

### ISSUE THREAD

**Issue by atomniketh** [semaphore-protocol/semaphore#321]
**Solution I'd like**

When using @semaphore-protocol/data, it would be helpful to have a function available to quickly evaluate if an identity.commitment is a member of a group.

It would be helpful if there were an option to be able to pass groupID and identity.commitment to a function that returns true/false:

`const isMember = await semaphoreEthers.isMember("42", "16948514235341957898454876473214737047419402240398321289450170535251226167324")
`

**Alternatives I've considered**
Presently, I have to do something like:

```
         await semaphoreEthers
           .getGroupMembers(groupIDNum)
           .then((allMembers) => {
             this.setState({ allMembers });
           });
          
          const activeCommitment = localStorage.getItem("identityCommitment");
          const { allMembers } = this.state;
          for (let i = 0; i < allMembers.length; i++) {
            if (allMembers[i] === activeCommitment) {
              console.log(`${ activeCommitment } exists in array`);
              break;
            }
          }
```

**Comment by cedoor** [comment]
Hi @atomniketh,

`SemaphoreEthers` would still need to fetch all the members. `SemaphoreSubgraph` could integrate a function like that without fetching all the group members though. Would it be useful for your use-case?

**Comment by atomniketh** [comment]
SemaphoreSubgraph would work too! It doesn't need to be SemaphoreEthers.
