### ISSUE TITLE
npm install sha3 dependency issue

### ISSUE THREAD

**Issue by oskarth** [semaphore-protocol/semaphore#33]
## Problem

> npm install
> ...
> Exit status 1
> Failed at the sha3@1.2.3 install script.

See https://github.com/phusion/node-sha3/issues/32 and https://github.com/phusion/node-sha3/pull/33 for more details

## Env

- Linux, Fedora 29
- npm 6.12.0
- node v13.0.1

**Comment by oskarth** [comment]
More like a workaround, I didn't investigate where the transitive dependency is loaded. It might work to upgrade web3/truffle/foo/bar etc too. This ensures the fixed version of sha3 is used for Node v10 and above.

---

EDIT: Workaround above only worked first time around, ran into more issues and the old version reappeared when running `npm install` again (node module shenanigans).

Workaround 2: Downgrade to Node v9 `nvm use 9`. This version is deprecated though. v8 Maintenance LTS EOL end of year (https://nodejs.org/en/about/releases/), but didn't try this one.

Best would be to extend sha3 version fix / bump other libs to run on up to date versions of Node.

**Comment by weijiekoh** [comment]
The install will work with Node 11.14.0. Unfortunately there are compilation issues with other versions like Node 12 LTE.
