### ISSUE TITLE
Change verification key points in contract to constant

### ISSUE THREAD

**Issue by saleel** [semaphore-protocol/semaphore#330]
The [`VK_POINTS` points variable](https://github.com/semaphore-protocol/semaphore/blob/main/packages/contracts/contracts/base/SemaphoreVerifier.sol#L29
) storing the verification key points in the contract is not a `constant`.

The value will be stored in storage slots and would require reading every time. If this could be changed to a `constant`, the value will be part of the bytecode and verification will be cheaper (and also better performance I think).

Since this is an array it cannot be marked as constant directly, so other techniques need to be explored.

**Comment by 0xshikhar** [comment]
Hey @cedoor, would love to work on this ? Could you clarify the remaining tasks for this issue? Any additional context would be appreciated. Thanks!

**Comment by cedoor** [comment]
Hi @0xshikhar, this issue is part of #354. Let's sync here: https://github.com/semaphore-protocol/semaphore/issues/345#issuecomment-2413395583

**Comment by cedoor** [comment]
@jimmychu0807 please, leave a comment here.

**Comment by jimmychu0807** [comment]
Hi

**Comment by 0xshikhar** [comment]
> Hi @0xshikhar, this issue is part of #354. Let's sync here: [#345 (comment)](https://github.com/semaphore-protocol/semaphore/issues/345#issuecomment-2413395583)

Sure, got it
