### ISSUE TITLE
cannnot create a project behind a proxy

### ISSUE THREAD

**Issue by zjingwang** [semaphore-protocol/semaphore#331]
**Describe the bug**
I was using this cli to create my own project behind a proxy, but got the error as below:

```
⠹ Creating your project in ./my-app/.npm-packages/lib/node_modules/@semaphore-protocol/cli/node_modules/make-fetch-happen/lib/agent.js:207
      new Error(`unsupported proxy protocol: '${proxyUrl.protocol}'`),
      ^
```

**To Reproduce**
use the cli 
```
semaphore create my-app --template monorepo-ethers
```

**Expected behavior**
project created successfully

**Screenshots**

**Technologies (please complete the following information):**

-   Node.js version
    v16.19.1
-   NPM version
    8.19.3
-   Solidity version
    solc, the solidity compiler commandline interface
    Version: 0.8.8+commit.dddeac2f.Linux.g++

**Additional context**

**Comment by vplasencia** [comment]
Hey @zjingwang ! Can you run the other cli commands successfully? Is the problem just the `create` command?

**Comment by zjingwang** [comment]
> Hey @zjingwang ! Can you run the other cli commands successfully? Is the problem just the `create` command?
just the  ``` create``` command for now

**Comment by vplasencia** [comment]
It seems that you can't access the npm registry under that proxy. Can you try running the `create` command using a VPN?

**Comment by zjingwang** [comment]
forget the cli. i just used the semaphore lib in my vue project, it woked fined except the ``` generateProof``` with error below:
![image](https://github.com/semaphore-protocol/semaphore/assets/46661079/1a28fd70-a92b-4188-a28a-2c8b9232a3fb)
is this a snarkjs problem or something else?

thanks for your time!

**Comment by vplasencia** [comment]
Yes, it could be related to snarkjs. How did you create your vue project? Using vite?

**Comment by vplasencia** [comment]
This can help: https://semaphore.appliedzkp.org/docs/troubleshooting#using-semaphore-in-the-frontend

**Comment by zjingwang** [comment]
yeah i am using vite+vue, but https://semaphore.appliedzkp.org/docs/troubleshooting#using-semaphore-in-the-frontend does not solve my problem, i'll try another way

**Comment by vplasencia** [comment]
Interesting. How did you create your project? To run the same things and check if I get the same error. Or what code are you trying to run?
