### ISSUE TITLE
StealthComms

### ISSUE THREAD

**Issue by atomniketh** [semaphore-protocol/semaphore#335]
**Describe your project**
StealthComms allows users to prove their membership in a group and send messages/signals without revealing their original identity. Built by extending Semaphore's whistleblower contract.

**Other info**

-   Name: StealthComms
-   Tagline: StealthComms allows users to prove their membership in a group and send messages/signals without revealing their original identity.

**Links**

-   Website: [https://stealthcomms.surge.sh/](https://stealthcomms.surge.sh/)
-   Github: [https://github.com/atomniketh/zk-app](https://github.com/atomniketh/zk-app)
-  Twitter: [https://twitter.com/AtomNikETH](https://twitter.com/AtomNikETH)

**Comment by vplasencia** [comment]
Hey @atomniketh! Great work and documentation. Thank you!
