### ISSUE TITLE
Update snarkjs version dependency

### ISSUE THREAD

**Issue by djma** [semaphore-protocol/semaphore#339]
**Describe the bug**
Looks like snarkjs must be >0.4.16 https://github.com/iden3/snarkjs#security
But semaphore-protocol/proof is at 0.4.13 https://github.com/semaphore-protocol/semaphore/blob/main/yarn.lock
https://github.com/semaphore-protocol/semaphore/blob/main/packages/proof/package.json

**Comment by cedoor** [comment]
@djma Thanks for pointing it out! We'll release a new minor version soon.
