### ISSUE TITLE
no range check for nLevels

### ISSUE THREAD

**Issue by 0x4ka5h** [semaphore-protocol/semaphore#340]
https://github.com/semaphore-protocol/semaphore/blob/7d26d4e66cabe9af76ed228b7dead8db1d0ba040/packages/circuits/semaphore.circom#L46

**Comment by vplasencia** [comment]
Hey @0x4ka5h! Thank you! That comment is for informational purposes.

**Comment by timou0911** [comment]
Hi @vplasencia! I'm interested in this Circom issue and would like to request an assignment. Thank you!

**Comment by cedoor** [comment]
Hey @timou0911, this issue is related to the old version of Semaphore, and that check shouldn't be necessary.

@vplasencia I think we can close this issue.

**Comment by vplasencia** [comment]
Hey @timou0911 as @cedoor mentioned this issue is related to Semaphore v3. Thank you very much 🙏

@cedoor! Agree. We can close this issue 👍
