### ISSUE TITLE
Remove Goerli from the supported networks

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/semaphore#352]
Goerli is [deprecated](https://ethereum.org/en/developers/docs/networks/#goerli) and will be replaced by [Holesovice](https://github.com/eth-clients/holesovice).

Goerli needs to be removed from the following packages ([semaphore repository](https://github.com/semaphore-protocol/semaphore)):

- [`@semaphore-protocol/data`](https://github.com/semaphore-protocol/semaphore/blob/main/packages/data)
- [`@semaphore-protocol/cli`](https://github.com/semaphore-protocol/semaphore/blob/main/packages/cli)

And from the following repositories:

- https://github.com/semaphore-protocol/subgraph ([`networks.json`](https://github.com/semaphore-protocol/subgraph/blob/main/networks.json), [`README.md`](https://github.com/semaphore-protocol/subgraph/blob/main/README.md))
- https://github.com/semaphore-protocol/website ([`en - deployed-contracts.md`](https://github.com/semaphore-protocol/website/blob/main/versioned_docs/version-V3/deployed-contracts.md), [`es - deployed-contracts.md`](https://github.com/semaphore-protocol/website/blob/main/i18n/es/docusaurus-plugin-content-docs/version-V3/deployed-contracts.md))

However, it makes sense to start working on this issue before releasing Semaphore v4, and in the meantime inform people that Goerli will not be supported anymore soon.

For now a solution can be to add an asterisk to `Goerli`, `Optimism Goerli` and `Arbitrum Goerli` on the [website](https://semaphore.pse.dev/docs/deployed-contracts), add a note like `The Goerli testnet is deprecated` and link the following websites for more information:

* Goerli: https://ethereum.org/en/developers/docs/networks/#goerli
* Optimism Goerli: https://community.optimism.io/docs/useful-tools/networks/#op-goerli 
* Arbitrum Goerli: https://docs.arbitrum.io/for-devs/concepts/public-chains#arbitrum-goerli

**Comment by sumitvekariya** [comment]
Hey, I would like to contribute to this one, 

only `goerli` should be remove from the supported networks? or `Arbitrum Goerli` & `Optimism Goerli` should also be removed?

**Comment by cedoor** [comment]
> only `goerli` should be remove from the supported networks? or `Arbitrum Goerli` & `Optimism Goerli` should also be removed?

Hey @sumitvekariya, only Goerli for now, as Arbitrum and Optimism are still migrating. I've added more info to the description. But the idea is to start working on this issue in Semaphore v4, and inform people that it is going to be deprecated soon in the doc in the meantime.

**Comment by sumitvekariya** [comment]
> > only `goerli` should be remove from the supported networks? or `Arbitrum Goerli` & `Optimism Goerli` should also be removed?
> 
> Hey @sumitvekariya, only Goerli for now, as Arbitrum and Optimism are still migrating. I've added more info to the description. But the idea is to start working on this issue in Semaphore v4, and inform people that it is going to be deprecated soon in the doc in the meantime.

Thanks for sharing all the details, I have created PR for adding warning and asterisk for the goerli networks in the meantime.

https://github.com/semaphore-protocol/website/pull/102

**Comment by sumitvekariya** [comment]
@cedoor Nothing more needs to do at this moment right? or I shall move forward with removing goerli from the packages mentioned by you?

**Comment by cedoor** [comment]
> @cedoor Nothing more needs to do at this moment right? or I shall move forward with removing goerli from the packages mentioned by you?

It's ok for now 👍🏽 Thank you for your PR 🙏🏽
