### ISSUE TITLE
Move the contracts extensions to an external repository

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/semaphore#353]
**Description**:

There were two extension contracts in Semaphore v3: https://github.com/semaphore-protocol/semaphore/tree/v3.15.2/packages/contracts/contracts/extensions

The idea is to use the latest Semaphore v4 to update those contracts and add them to the `Semaphore Extensions` repo: https://github.com/semaphore-protocol/extensions

**Comment by Dozie2001** [comment]
Is this issue still open?

**Comment by cedoor** [comment]
@Dozie2001 it is!

**Comment by Dozie2001** [comment]
Hello @cedoor just to be clear I am just updating the [Extensions repo](https://github.com/semaphore-protocol/extensions) using v4 nothing else correct?

**Comment by cedoor** [comment]
> Hello @cedoor just to be clear I am just updating the [Extensions repo](https://github.com/semaphore-protocol/extensions) using v4 nothing else correct?

Nothing else, the package should have the same structure as `package/contracts` in the [main semaphore repo](https://github.com/semaphore-protocol/semaphore).
