### ISSUE TITLE
Circom 2.1.0 Anonymous Components and Tuples

### ISSUE THREAD

**Issue by moven0831** [semaphore-protocol/semaphore#365]
I'm wondering if this concern is appropriate for the current project. I've observed a similar update in another protocol, which prompted me to raise the issue here.

As mentioned in Circom 2.1.0: https://docs.circom.io/circom-language/anonymous-components-and-tuples/

Refactoring the circom code with anonymous components will enhance code readability.

In current version, we have to assign inputs into template by elements
```circom
template A(n){
   signal input a, b;
   signal output c;
   c <== a*b;
}
template B(n){
   signal input in[n];
   signal out;
   component temp_a = A(n);
   temp_a.a <== in[0]; 
   temp_a.b <== in[1];
   out <== temp_a.c;
}
component main = B(2);
```

with upgrade to Circom 2.1.0, the anonymous components feature can assign inputs and generate constraints within a line of code.
```circom
template A(n){
   signal input a, b;
   signal output c;
   c <== a*b;
}
template B(n){
   signal input in[n];
   signal out <== A(n)(in[0],in[1]);
}
component main = B(2);
```

**Comment by cedoor** [comment]
Hi @moven0831, the new circuits in Semaphore v4 will use those new Circom features -> https://github.com/semaphore-protocol/research/blob/main/circom/semaphore-v4/index.circom

**Comment by moven0831** [comment]
> Hi @moven0831, the new circuits in Semaphore v4 will use those new Circom features -> https://github.com/semaphore-protocol/research/blob/main/circom/semaphore-v4/index.circom

Amazing, v4 circom code have nice readability. Thanks for the information. I'll make sure to check the research repo🫡

**Comment by cedoor** [comment]
> Amazing, v4 circom code have nice readability. Thanks for the information. I'll make sure to check the research repo🫡

No problem. I agree with you that code readability is very important 👍🏽
