### ISSUE TITLE
Add pure verification method

### ISSUE THREAD

**Issue by saleel** [semaphore-protocol/semaphore#366]
The `verifyProof()` method currently does a little more that just proof verification - it store the nullifier in the contract (to prevent verifyProof being called again with same proof).

But there could be use cases where one would want to simply verify the proof - maybe even offchain, and also verify multiple time. Currently this is possible by calling the Verifier contract directly, but the caller would need to get group merkleRoot (and other data ) by calling Semaphore contract first. Additionally they will need to check if the proof was computed using an old merkleRoot themselves (which is already implemented in `verifyProof`).

We can add another method that does only verification without doing any state changes (saving the nullifier). In fact, this method could be called `verifyProof`, and the current `verifyProof` could be something like `validateProof()` (like validating a ticket which could be done only once).

**Comment by cedoor** [comment]
I think this makes a lot of sense 👍🏽  I already created an issue for it here #329. I'll close this one and add a reference there to your description.

Please feel free to open a PR if you want!

**Comment by saleel** [comment]
Oh right, sorry. I remember we creating it, but couldn't find it when I searched yesterday.
