### ISSUE TITLE
Carousels don't work if you click on "next" or "previous" right after the page loads

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#432]

**Comment by sumitvekariya** [comment]
Hey, can you please add the description and how to reproduce it? I can help on this issue.

**Comment by cedoor** [comment]
Hey @sumitvekariya, this is an issue that we were already working on and quite unstable. Please check the list here for good first issues: https://github.com/orgs/semaphore-protocol/projects/10/views/20

Thanks 🙏
