### ISSUE TITLE
Create a Semaphore package that includes the core packages

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#461]
**Description**:

Typically, developers working with the Semaphore protocol tend to utilize its core packages in conjunction: `@semaphore-protocol/proof`, `@semaphore-protocol/identity`, and `@semaphore-protocol/group`. This common practice stems from the interrelated functionality of these packages, which are often used in tandem to achieve comprehensive solutions in Semaphore-based projects.

Introducing a single, unified package (`@semaphore-protocol/core`) that consolidates all the functions from these individual core packages would significantly streamline the development process.

The core package would be an additional one. Devs could still use specific packages if they need them.

**Tasks**:

- [x] Create a specific `exports` path for each package in the `package.json`

**Comment by 0xjei** [comment]
Hey @cedoor, I totally agree! Not only is it a very convenient shorthand, but it also makes onboarding much easier. Many other projects follow this approach, so my agreement is more than unanimous.

**Comment by vplasencia** [comment]
Hey @cedoor! I think it is a great idea. It will be easier for developers because they will only install one package, and they will also have the option to import them separately in case they prefer to use them separately.
