### ISSUE TITLE
FixedVerifier test does not work

### ISSUE THREAD

**Issue by ceyonur** [semaphore-protocol/semaphore#49]
I believe FixedVerifier test should be based on `verifier.sol` contract instead of `Semaphore.sol` & `SemaphoreClient.sol`.
Parameters given to `preBroadcastCheck` and `broadcastSignal` are not compatible with contracts.
https://github.com/appliedzkp/semaphore/blob/1e34d21f989550bb10c1a356e045770dfd4b0a6d/contracts/ts/__tests__/FixedVerifier.test.ts#L163-L172

Is there a prior version of this test? Or am I missing something?

BTW, I'm porting tests and contracts to truffle/hardhat environment (instead of etherlime).

**Comment by cedoor** [comment]
@ceyonur Hi, really sorry for this late reply! Semaphore has been updated and this issue is a bit outdated now. If you need help with Semaphore v2 please open another issue :)
