### ISSUE TITLE
Semaphore article to resources

### ISSUE THREAD

**Issue by TheBojda** [semaphore-protocol/semaphore#500]
I wrote a short (and I hope informative) article about Semaphore. If you think it's good enough, please add it to the resources page.

My pull request: https://github.com/semaphore-protocol/website/pull/111

**Comment by vplasencia** [comment]
Hey @TheBojda. It is a great article, thank you for writing it. Your article is in the list of articles in the new Semaphore website we are working on:
https://github.com/semaphore-protocol/semaphore/blob/chore/website/apps/website/src/data/articles.json#L31

Would you like to change the article info there like title, date and url or is it ok to have the other article?

**Comment by TheBojda** [comment]
Thank you very much. Everything is fine for me. :)
