### ISSUE TITLE
Prettier doesn't format MDX files properly

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/semaphore#503]

**Comment by sripwoud** [comment]
@vplasencia 
Is this still a valid issue?
I can't reproduce it.  
I tried:
- Turn an mdx file into a file with invalid format. e.g add a `;` somewhere in `docs/src/components/Articles.tsx`
- `yarn prettier:write`
- file was formatted as expected

**Comment by vplasencia** [comment]
Hey @sripwoud! I think it's still an issue. The easiest way to reproduce it is to comment this line: https://github.com/semaphore-protocol/semaphore/blob/main/.prettierignore#L33, then run: `yarn prettier:write`, then go inside `apps/docs` and run `yarn start`. You should see some errors. Let me know if you don't see any errors.

**Comment by sripwoud** [comment]
Ups yeah my bad, I had tweaked an tsx file :man_facepalming:
