### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by andyguzmaneth** [semaphore-protocol/semaphore#515]

**Comment by SofiiaVarich** [comment]
Hey. Can you provide a list of the words or text that needs to be translated?

**Comment by cedoor** [comment]
> Hey. Can you provide a list of the words or text that needs to be translated?

Hey, you can see an example here (Spanish) -> [`en`](https://github.com/semaphore-protocol/website/tree/main/i18n/es). You should basically create another directory for Chinese and keep the same file structure.

You should also add `zk` in this list -> https://github.com/semaphore-protocol/website/blob/cfab949e2ab476b23663464ba68043fbf73d9d17/docusaurus.config.js#L24

If you want to test it locally you can create a command like this -> https://github.com/semaphore-protocol/website/blob/cfab949e2ab476b23663464ba68043fbf73d9d17/package.json#L7

**Comment by SofiiaVarich** [comment]
Okay thank you. I will check it out.

**Comment by vplasencia** [comment]
Hey @SofiiaVarich! Great! If you have more questions, please let us know.
