### ISSUE TITLE
Make caurosels horizontally scrollable in the website

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#562]

**Comment by 0xgun** [comment]
@cedoor  can I work on this issue?

**Comment by cedoor** [comment]
> @cedoor can I work on this issue?

Hey @0xgun, sure you can! Make sure to read our [contributing](https://github.com/semaphore-protocol/semaphore/blob/main/CONTRIBUTING.md) file.

**Comment by intldds** [comment]
Hi @0xgun are you still working on this? 👀 I think I found a way to do it

**Comment by 0xgun** [comment]
Hey! @intldds I'm not working on it right now, you can carry on with this issue.

**Comment by intldds** [comment]
Added a [PR](https://github.com/semaphore-protocol/semaphore/pull/639) @cedoor :) I've basically only added [one line](https://github.com/semaphore-protocol/semaphore/pull/639/files) and it should work fine!

**Comment by whoisgautxm** [comment]
Is this issue still open?

**Comment by vplasencia** [comment]
Hey @whoisgautxm yes. Do you want me to assign you this issue?

**Comment by whoisgautxm** [comment]
yes i am working on it
![image](https://github.com/semaphore-protocol/semaphore/assets/129857715/cc9211de-f994-4b3b-b92a-74a6283d5d58)

**Comment by whoisgautxm** [comment]
yes i am working on it 
Just want to make sure that this is the caurosels you are talking about 
![image](https://github.com/semaphore-protocol/semaphore/assets/129857715/2047b5aa-de38-4802-9680-8bdbf62dc7aa)

**Comment by vplasencia** [comment]
Hey @whoisgautxm 

Yes, correct, that's the carousel.
