### ISSUE TITLE
Consider `pnpm` as a new package manager for the monorepo

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#565]

**Comment by 0xjei** [comment]
We are currently considering whether to upgrade our monorepos to `yarn v4` or switch to another package manager such as `pnpm` or `bun`. The latest Yarn release,

- [Yarn V4](https://yarnpkg.com/blog/release/4.0), offers some cool features such as Hardened Mode, JavaScript Constraints, native TS integration, better UI, and improved performance (similar to pnpm).
- There is an [interesting conversation](https://www.reddit.com/r/typescript/comments/1ainj58/pnpm_vs_yarn_v4/) about this topic on Reddit.
- The [PNPM benchmarks](https://pnpm.io/benchmarks) provide valuable information.
- Comparing `pnpm`, `yarn` and `npm` in [this article](https://pnpm.io/feature-comparison), it seems that Yarn V4 is suitable for our current monorepos.

Imho, we do not have complex pipelines or performance issues that would benefit from `pnpm`'s slightly better performance/features (e.g. side-effects cache, auto-installing peers) but I'd love to hear your takes here.

@cedoor @vplasencia or anyone else that'd like to chime in!

**Comment by cedoor** [comment]
@0xjei Considering those points, I think we all agree that Yarn V4 is fine for Semaphore.

Thanks for putting that information together!

If @vplasencia agrees, we can close this issue.

**Comment by vplasencia** [comment]
Yes, I agree. Let's close this issue 👍
