### ISSUE TITLE
`generateProof` workers won't exit

### ISSUE THREAD

**Issue by pooryamoh** [semaphore-protocol/semaphore#579]
**Describe the bug**
Wrote simple test code, for generating proof off-chain, after generating proof code won't exit and stop 

**To Reproduce**
My Code:

```const hre = require("hardhat");
const cljs = require("circomlibjs");
const { Identity } = require("@semaphore-protocol/identity");
const { Group } = require("@semaphore-protocol/group");
const {
  generateProof,
  verifyProof,
  calculateNullifierHash,
} = require("@semaphore-protocol/proof");

async function main() {
  const identity = new Identity("secret");
  const groupId = 1;
  const externalNullifier = 1212;
  const signal = 1;

  const group = new Group(groupId, 17);

  group.addMember(identity.commitment);

  const fullProof = await generateProof(
    identity,
    group,
    externalNullifier,
    signal,
    {
      zkeyFilePath: "./semaphore.zkey",
      wasmFilePath: "./semaphore.wasm",
    }
  );
  console.log(fullProof);
}
main();
```

**Expected behavior**
Logging `fullProof` and exit.

**Screenshots**
![image](https://github.com/semaphore-protocol/semaphore/assets/44756120/2f68ff90-3715-474b-9ff1-4be8da34eb26)

**Technologies (please complete the following information):**

-   Node.js v18.12.1
-   NPM 9.6.2
-   @semaphore-protocol/contracts 3.15.2
-   @semaphore-protocol/group 3.15.2
-   @semaphore-protocol/identity 3.15.2
-   @semaphore-protocol/proof 3.15.2
-   OS windows 11

**Comment by vplasencia** [comment]
Hey @pooryamoh!

Here is more context about the issue you have: https://github.com/semaphore-protocol/semaphore/issues/318

A temporal solution could be to do something like this:

```ts
main().finally(() => process.exit());
```
