### ISSUE TITLE
Remove `prepublish` script in the CLI monorepo templates from the published package

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#591]
## Description

The idea is to remove the `prepublish` script from the `scripts` object of the `package.json` file of every cli template when the template is downloaded using the CLI. 

## Context

- [`cli-template-contracts-hardhat` `prepublish` script](https://github.com/semaphore-protocol/semaphore/blob/main/packages/cli-template-contracts-hardhat/package.json#L33)

- [`cli-template-monorepo-ethers` `prepublish` script](https://github.com/semaphore-protocol/semaphore/blob/main/packages/cli-template-monorepo-ethers/package.json#L21)

- [`cli-template-monorepo-subgraph` `prepublish` script](https://github.com/semaphore-protocol/semaphore/blob/main/packages/cli-template-monorepo-subgraph/package.json#L21)

When the templates are downloaded using the [Semaphore CLI](https://github.com/semaphore-protocol/semaphore/tree/main/packages/cli), it would be nice to remove the `prepublish` script since it's not necessary for the applications that developers will create with the templates.

Before [printing the project scripts](https://github.com/semaphore-protocol/semaphore/blob/main/packages/cli/src/index.ts#L117), the `prepublish` script can be removed programmatically so that it's not part of the `package.json` of the downloaded project and it is also not part of the available scripts.

**Comment by 0xshikhar** [comment]
Hey @cedoor , would like to work on this task. Could you clarify the remaining tasks for this issue? Any additional context would be appreciated. Thanks!

**Comment by vplasencia** [comment]
Hey @0xshikhar! I just updated the issue description. Would you like me to assign you this issue? Please, let us know if you have any questions.

**Comment by 0xshikhar** [comment]
Sure, i am happy to solve this issue.

**Comment by vplasencia** [comment]
Hey @0xshikhar! I just assigned the issue to you.
