### ISSUE TITLE
Show Yarn instead of NPM in the CLI `create` command messages

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#592]
**Description**:

The CLI [`create`](https://github.com/semaphore-protocol/semaphore/blob/c00b0075049b1bf00d22b4ce180bd382f625038c/packages/cli/src/index.ts#L50) command allows devs to init a project by downloading a template and showing some instructions for installing and using it.

The current command shows a list of NPM commands but the CLI monorepo templates are actually using Yarn.

**Comment by swellander** [comment]
I can take this one!

**Comment by cedoor** [comment]
> I can take this one!

Hey @swellander, it would be great! I've added a description, let me know if you need any additional info.
