### ISSUE TITLE
Translate V4 documentation to Spanish

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#603]
### Previous work
https://github.com/semaphore-protocol/semaphore/pull/627

**Comment by intldds** [comment]
@vplasencia do you think you can assign it to me please?

**Comment by vplasencia** [comment]
Hey @intldds, done! ✅

Thank you so much.

**Comment by carlos-israelj** [comment]
Hi! @vplasencia @aguzmant103 is this issue still issues? Could I take it? I am part of the PSE 2024 core program

**Comment by vplasencia** [comment]
Hey @cijimenez! 👋 

Thank you very much for the interest. There will be some improvements in the Semaphore documentation soon, so it won't be stable. Then it's better to close the issues related to translations for now. Sorry about it and feel free to pick another issue or ask any questions.
