### ISSUE TITLE
Add these new videos to the Semaphore website

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/semaphore#610]
https://youtu.be/WEKqycIMmLY

https://youtu.be/tx1Xglf07yE

**Comment by dicethedev** [comment]
@vplasencia please give more context on this issue. Thank you!

**Comment by vplasencia** [comment]
Hey @dicethedev 

Yes, sure. In the Semaphore website, there is a list of resources. In this json file, you can find all the videos:
https://github.com/semaphore-protocol/semaphore/blob/main/apps/website/src/data/videos.json

The idea is to add these two new videos to the list of resources.

The date for the first video is "2023-11-16" and for the second is "2024-02-02"

**Comment by dicethedev** [comment]
@vplasencia Thank you for the clarity. I will look into this!

**Comment by vplasencia** [comment]
Hey @dicethedev do you want me to assign you this issue?

**Comment by mabsattar** [comment]
Hi, I would like to work on this, can you please assign me.

**Comment by dicethedev** [comment]
> Hey @dicethedev do you want me to assign you this issue?

yes!

**Comment by dicethedev** [comment]
@vplasencia    

```
 {
       "title": "Building with Semaphore",
        "eventName": "ETHRome",
        "date": "2024-02-02",
        "speakers": ["Vivian Plasencia"],
        "url": "https://youtu.be/tx1Xglf07yE",
        "thumbnail": "https://img.youtube.com/vi/4e4EAdu0WVg/0.jpg"
    }
```

did you want the title,  eventName, and speakers, to be the same?

**Comment by vplasencia** [comment]
Hey @dicethedev 

The other properties should be updated according to the video. In that case, the title of that video is "Semaphore: The Power of Anonymity", the event name is "ETHGlobal Circuit Breaker" and the speakers property is the same. Let us know if you have more questions.

**Comment by vplasencia** [comment]
Hey! @mabsattar 

Someone is already working on this. Thank you so much for your interest. We will create more good first issues like this. Feel free to let us know if you have a specific preference regarding the type of issues (documentation, contracts, etc.).

**Comment by dicethedev** [comment]
@

> Hey @dicethedev
> 
> The other properties should be updated according to the video. In that case, the title of that video is "Semaphore: The Power of Anonymity", the event name is "ETHGlobal Circuit Breaker" and the speakers property is the same. Let us know if you have more questions.


I just added it - https://github.com/semaphore-protocol/semaphore/pull/613
