### ISSUE TITLE
Update Docs font

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/semaphore#624]
**Describe the bug**
The font in the documentation is not displayed correctly for all devices/browsers. 

More context: 
https://discord.com/channels/1019327562964553808/1078431018316464189/1205604904241070120

**Comment by troopdegen** [comment]
Hello, the issue is happening on a Windows desktop (Windows 10 Pro) + Google Chrome explorer.

On my Mac laptop, font is different (more readable), which I assume is the desired one.

Thanks for looking into this.

**Comment by cedoor** [comment]
@angelmc32 Could you double-check if it works fine now in your browser? It should need a few minutes to deploy.

Otherwise, we'll re-open this issue.

**Comment by troopdegen** [comment]
Hi @cedoor, I can confirm, the font has changed to the same as MacOS. There is a brief "loading" period where you can see the previous font, but I assume it's while the proper font is loaded.

In any case, thanks for looking into this! I had been working on my laptop so I didn't have a chance to check the Windows PC before.
