### ISSUE TITLE
`onlyExistingGroup(groupId) onlyGroupAdmin(groupId)` can be reduced to `onlyGroupAdmin(groupId)`

### ISSUE THREAD

**Issue by 0xbok** [semaphore-protocol/semaphore#680]
**Describe the improvement you're thinking about**
`onlyExistingGroup(groupId) onlyGroupAdmin(groupId)` checks that a group exists and the `msg.sender` is the group admin. Just checking for `onlyGroupAdmin(groupId)` is sufficient for this case as a group exists only when the group has a non-zero admin. Thus, if we ensure `msg.sender` is the admin, we implicitly ensure that the admin is non-zero.

One of the many places where the 2 modifiers are used together: https://github.com/semaphore-protocol/semaphore/blob/v4.0.0-beta.1/packages/contracts/contracts/base/SemaphoreGroups.sol#L61

**Additional context**
PSE audit

**Comment by cedoor** [comment]
Assigned to @zkfriendly
