### ISSUE TITLE
Multiple `onlyExistingGroup(groupId)` checks

### ISSUE THREAD

**Issue by 0xbok** [semaphore-protocol/semaphore#681]
**Describe the improvement you're thinking about**
[`validateProof()`](https://github.com/semaphore-protocol/semaphore/blob/v4.0.0-beta.1/packages/contracts/contracts/Semaphore.sol#L106C25-L106C51) checks for existing group which then calls [`verifyProof()`](https://github.com/semaphore-protocol/semaphore/blob/v4.0.0-beta.1/packages/contracts/contracts/Semaphore.sol#L137) which agains ensures group's existence.

Remove `onlyExistingGroup(groupId)` modifier on [`validateProof()`](https://github.com/semaphore-protocol/semaphore/blob/v4.0.0-beta.1/packages/contracts/contracts/Semaphore.sol#L106C25-L106C51)

**Additional context**
PSE audit.

**Comment by cedoor** [comment]
Assigned to @zkfriendly
