### ISSUE TITLE
define a const variable for max_depth

### ISSUE THREAD

**Issue by 0xDatapunk** [semaphore-protocol/semaphore#683]
It is better to define a const for 12

https://github.com/semaphore-protocol/semaphore/blob/8eb19e83fda62644872b2fcfbd85011d3b2c21e2/packages/contracts/contracts/Semaphore.sol#L139

**Comment by 0xbok** [comment]
since `12` will be updated as max depth is increased, it's better to define it as a const variable. It highlights the use of the constant and there is lower chances of forgetting it in case a modification is needed.
