### ISSUE TITLE
missing admin access check

### ISSUE THREAD

**Issue by 0xDatapunk** [semaphore-protocol/semaphore#689]
the _addMember function is missing `onlyGroupAdmin(groupId)` check, Without it anyone can add to the group.

https://github.com/semaphore-protocol/semaphore/blob/8eb19e83fda62644872b2fcfbd85011d3b2c21e2/packages/contracts/contracts/base/SemaphoreGroups.sol#L83

**Comment by cedoor** [comment]
Assigned to @zkfriendly
