### ISSUE TITLE
Use `maybeGetSemaphoreSnarkArtifacts` from `@zk-kit/utils`

### ISSUE THREAD

**Issue by sripwoud** [semaphore-protocol/semaphore#746]
Once https://github.com/privacy-scaling-explorations/zk-kit/pull/240 merges and the corresponding new `@zk-kit/utils` package is published, we can delete all that code
https://github.com/semaphore-protocol/semaphore/blob/main/packages/proof/src/get-snark-artifacts.browser.ts
https://github.com/semaphore-protocol/semaphore/blob/main/packages/proof/src/get-snark-artifacts.node.ts

and use `maybeGetSemaphoreSnarkArtifacts` instead

**Comment by sripwoud** [comment]
Please assign this to me ^^

**Comment by vplasencia** [comment]
Hey @sripwoud! Done. Thanks.
