### ISSUE TITLE
Publish `@semaphore-protocol/contracts` as a package in the `soldeer` package registry. 

### ISSUE THREAD

**Issue by ultraviolet10** [semaphore-protocol/semaphore#800]
It would be ideal to be able to easily install the semaphore contracts as a dependency in any Foundry project. [Soldeer](https://soldeer.xyz/) is a [recently introduced](https://github.com/foundry-rs/foundry/commit/169f83fcb8252fa37f642c1e77a22640e95f0864) package manager for Foundry. 

Soldeer outlines the process for publishing a set of contracts as a package [here](https://book.getfoundry.sh/projects/soldeer). For any additional help, I believe the team may provide more context into how to seamlessly achieve this.

**Comment by sripwoud** [comment]
Semaphore contracts are finally available on soldeer btw
https://soldeer.xyz/project/semaphore-protocol-contracts

**Comment by cxrtisxl** [comment]
@sripwoud 
Installing `semaphore-protocol-contracts` with Soldeer doesn't bring `@zk-kit` to the project, making it impossible to compile.
