### ISSUE TITLE
Failed to install V2

### ISSUE THREAD

**Issue by twjjw** [semaphore-protocol/semaphore#81]
D:\data\node2-react\react-auth-box>npm i @zk-kit/identity @zk-kit/protocols @semaphore/contracts --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@semaphore%2fcontracts - Not found
npm ERR! 404
npm ERR! 404  '@semaphore/contracts@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\twj\AppData\Roaming\npm-cache\_logs\2022-02-11T06_59_08_499Z-debug.log

**Comment by twjjw** [comment]
获取不到 这个@semaphore/contracts

**Comment by cedoor** [comment]
Hi @twjjw , the contracts' package is `@appliedzkp/semaphore-contracts` now. Sorry we are updating documentation and packages very frequently, soon they will be more stable
