### ISSUE TITLE
Create a page in the doc to list all benchmarks

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#815]

**Comment by Dozie2001** [comment]
Hello @cedoor interested in working on this can I geta assigned?

**Comment by vplasencia** [comment]
Hey @Dozie2001 thank you very much for the interest. I will take this issue since we have a tight deadline for it because of the Semaphore v4 stable release but feel free to ask for any other issue you find interesting. Thank you 🙏

**Comment by Dozie2001** [comment]
No problem
