### ISSUE TITLE
Specify artifacts version in `@semaphore-protocol/proof` package

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#825]
**Description**

The version of the ZK artifacts to download when generating a proof needs to be specified, as the latest version will be used by default, and when a new version is released the old version would still point to the latest, which would no longer be the right version.

**Comment by sripwoud** [comment]
What we want is to pass a hardcoded `version` parameter to the `maybeGetSnarkArtifacts` function [here](https://github.com/semaphore-protocol/semaphore/blob/57747467bda7d799d6844a774a0a8f7e87b4ef21/packages/proof/src/generate-proof.ts#L86), correct?
Where version is one of the `@zk-kit/semaphore-artifacts` version published in npm?
```
curl https://registry.npmjs.com/@zk-kit/semaphore-artifacts | jq '.versions | keys'
```

What would be the best way?
- hardcoding in line like:
   ```diff
   -     snarkArtifacts ??= await maybeGetSnarkArtifacts(Project.SEMAPHORE, { parameters: [merkleTreeDepth] })
   +     snarkArtifacts ??= await maybeGetSnarkArtifacts(Project.SEMAPHORE, { parameters: [merkleTreeDepth], version: '4.0.0-beta.11' })

   ```
   
 - having a custom field in the package json and reading it to pass it to `maybeGetSnarkArtifacts`, e.g.
    ```diff
    -     snarkArtifacts ??= await maybeGetSnarkArtifacts(Project.SEMAPHORE, { parameters: [merkleTreeDepth] })
    +     const { artifactsVersion: version } = JSON.parse(readFileSync('../package.json', 'utf8')) 
    +     snarkArtifacts ??= await maybeGetSnarkArtifacts(Project.SEMAPHORE, { parameters: [merkleTreeDepth], version })
    ```
    
  - we stop defaulting to `latest` [here](https://github.com/privacy-scaling-explorations/snark-artifacts/blob/7d47be4dd0288e177260ee1e081c223837912a53/packages/artifacts/src/download/index.browser.ts#L15), and make `version` a required parameter of `generateProof` (breaking change) (worse UX imo)

**Comment by cedoor** [comment]
@sripwoud 

I tend to prefer the first option. Re the third, are there any use cases where a package needs the latest?

**Comment by sripwoud** [comment]
Closed by https://github.com/semaphore-protocol/semaphore/pull/826/commits/9f6516c060de803545bcaa7e415cabaafaa81527
