### ISSUE TITLE
imported group.indexOf not work

### ISSUE THREAD

**Issue by tochy-open** [semaphore-protocol/semaphore#847]
**Describe the bug**
After group imported, members return string[]
indexOf function always return -1

**To Reproduce**

const group_origin = new Group([1n, 2n, 3n, 4n, 5n])
const exported = group_origin.export()
console.log('group test', group_origin.members)
console.log(group_origin.indexOf(3n))
console.log(group_origin.indexOf('3'))
console.log(group_origin.indexOf(BigInt('3')))
console.log(group_origin.members.indexOf(3n))
console.log(group_origin.members.indexOf(BigInt('3')))

const group = Group.import(exported)
console.log('group imported', group.members)
console.log(group.indexOf(3n))
console.log(group.indexOf('3'))
console.log(group.indexOf(BigInt('3')))
console.log(group.members.indexOf(3n))
console.log(group.members.indexOf(BigInt('3')))

const converted = group.members.map(id => id.toString())
console.log('members bigint[] to string[]')
console.log(converted.indexOf('3'))

**Expected behavior**
imported group.indexOf return correct position

**Screenshots**

![Screenshot 2024-08-06 at 2 29 17 PM](https://github.com/user-attachments/assets/e3df2ee2-d439-418b-bfe4-78aee69071d3)

**Comment by cedoor** [comment]
Thanks @tochy-open 🙏🏽  WIP

Re: https://github.com/privacy-scaling-explorations/zk-kit/pull/313
