### ISSUE TITLE
Add documentation about import/export functions of the identity package

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#872]
## Description

The idea is to add to the Semaphore docs the way to export and import a Semaphore v4 Identity.

## Context

This issue was created as part of the feedback at ETHRome 2024.

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
