### ISSUE TITLE
cli create contracts-foundry template does not download properly

### ISSUE THREAD

**Issue by jimmychu0807** [semaphore-protocol/semaphore#926]
Running `npx @semaphore-protocol/cli create test-foundry` yields the following:

```
$ npx @semaphore-protocol/cli create test-foundry

? Select one of the supported templates: contracts-foundry (Foundry)
 ⠦ Creating your project in ./test-foundrynode:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '~/src/hkwtf/semaphore-aa/test-foundry/files.tgz'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '~/src/hkwtf/semaphore-aa/test-foundry/files.tgz'
}

Node.js v20.11.0
```

I will look into this. Feel free to assign it to me.

**Comment by vplasencia** [comment]
Hey @jimmychu0807 thank you very much for creating the issue. This should be solved in `v4.8.1`. This `prepublish` script was missing: https://github.com/semaphore-protocol/semaphore/pull/927/files#diff-f510080d350f38b28e83b2b962ef8def0ebcd3d36a942cbca7b33e7017dae838R27

Can you try again and let me know?

**Comment by jimmychu0807** [comment]
@vplasencia just tested and it works fine now. Thanks for the fix.

**Comment by vplasencia** [comment]
@jimmychu0807 great! Thank you!
